// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestV3.Data;

#nullable disable

namespace TestV3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250411035335_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestV3.Models.PmQL.FmpA0", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Column0h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_0h30");

                    b.Property<string>("Column10h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_10h");

                    b.Property<string>("Column10h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_10h30");

                    b.Property<string>("Column11h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_11h");

                    b.Property<string>("Column11h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_11h30");

                    b.Property<string>("Column12h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_12h");

                    b.Property<string>("Column12h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_12h30");

                    b.Property<string>("Column13h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_13h");

                    b.Property<string>("Column13h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_13h30");

                    b.Property<string>("Column14h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_14h");

                    b.Property<string>("Column14h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_14h30");

                    b.Property<string>("Column15h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_15h");

                    b.Property<string>("Column15h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_15h30");

                    b.Property<string>("Column16h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_16h");

                    b.Property<string>("Column16h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_16h30");

                    b.Property<string>("Column17h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_17h");

                    b.Property<string>("Column17h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_17h30");

                    b.Property<string>("Column18h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_18h");

                    b.Property<string>("Column18h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_18h30");

                    b.Property<string>("Column19h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_19h");

                    b.Property<string>("Column19h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_19h30");

                    b.Property<string>("Column1h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_1h");

                    b.Property<string>("Column1h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_1h30");

                    b.Property<string>("Column20h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_20h");

                    b.Property<string>("Column20h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_20h30");

                    b.Property<string>("Column21h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_21h");

                    b.Property<string>("Column21h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_21h30");

                    b.Property<string>("Column22h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_22h");

                    b.Property<string>("Column22h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_22h30");

                    b.Property<string>("Column23h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_23h");

                    b.Property<string>("Column23h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_23h30");

                    b.Property<string>("Column24h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_24h");

                    b.Property<string>("Column2h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_2h");

                    b.Property<string>("Column2h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_2h30");

                    b.Property<string>("Column3h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_3h");

                    b.Property<string>("Column3h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_3h30");

                    b.Property<string>("Column4h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_4h");

                    b.Property<string>("Column4h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_4h30");

                    b.Property<string>("Column5h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_5h");

                    b.Property<string>("Column5h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_5h30");

                    b.Property<string>("Column6h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_6h");

                    b.Property<string>("Column6h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_6h30");

                    b.Property<string>("Column7h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_7h");

                    b.Property<string>("Column7h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_7h30");

                    b.Property<string>("Column8h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_8h");

                    b.Property<string>("Column8h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_8h30");

                    b.Property<string>("Column9h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_9h");

                    b.Property<string>("Column9h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_9h30");

                    b.Property<string>("Giá")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ngày")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tổng")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__FMP_A0__3214EC07FFE266CC");

                    b.ToTable("FMP_A0", (string)null);
                });

            modelBuilder.Entity("TestV3.Models.PmQL.FmpEvn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChuKy0h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_0h30");

                    b.Property<double?>("ChuKy10h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h");

                    b.Property<double?>("ChuKy10h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h30");

                    b.Property<double?>("ChuKy11h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h");

                    b.Property<double?>("ChuKy11h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h30");

                    b.Property<double?>("ChuKy12h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h");

                    b.Property<double?>("ChuKy12h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h30");

                    b.Property<double?>("ChuKy13h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h");

                    b.Property<double?>("ChuKy13h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h30");

                    b.Property<double?>("ChuKy14h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h");

                    b.Property<double?>("ChuKy14h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h30");

                    b.Property<double?>("ChuKy15h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h");

                    b.Property<double?>("ChuKy15h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h30");

                    b.Property<double?>("ChuKy16h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h");

                    b.Property<double?>("ChuKy16h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h30");

                    b.Property<double?>("ChuKy17h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h");

                    b.Property<double?>("ChuKy17h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h30");

                    b.Property<double?>("ChuKy18h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h");

                    b.Property<double?>("ChuKy18h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h30");

                    b.Property<double?>("ChuKy19h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h");

                    b.Property<double?>("ChuKy19h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h30");

                    b.Property<double?>("ChuKy1h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h");

                    b.Property<double?>("ChuKy1h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h30");

                    b.Property<double?>("ChuKy20h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h");

                    b.Property<double?>("ChuKy20h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h30");

                    b.Property<double?>("ChuKy21h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h");

                    b.Property<double?>("ChuKy21h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h30");

                    b.Property<double?>("ChuKy22h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h");

                    b.Property<double?>("ChuKy22h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h30");

                    b.Property<double?>("ChuKy23h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h");

                    b.Property<double?>("ChuKy23h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h30");

                    b.Property<double?>("ChuKy24h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_24h");

                    b.Property<double?>("ChuKy2h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h");

                    b.Property<double?>("ChuKy2h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h30");

                    b.Property<double?>("ChuKy3h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h");

                    b.Property<double?>("ChuKy3h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h30");

                    b.Property<double?>("ChuKy4h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h");

                    b.Property<double?>("ChuKy4h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h30");

                    b.Property<double?>("ChuKy5h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h");

                    b.Property<double?>("ChuKy5h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h30");

                    b.Property<double?>("ChuKy6h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h");

                    b.Property<double?>("ChuKy6h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h30");

                    b.Property<double?>("ChuKy7h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h");

                    b.Property<double?>("ChuKy7h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h30");

                    b.Property<double?>("ChuKy8h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h");

                    b.Property<double?>("ChuKy8h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h30");

                    b.Property<double?>("ChuKy9h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h");

                    b.Property<double?>("ChuKy9h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h30");

                    b.Property<string>("Gia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int");

                    b.Property<double?>("Tong")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__FMP_EVN__3214EC27F7A0AD91");

                    b.ToTable("FMP_EVN", (string)null);
                });

            modelBuilder.Entity("TestV3.Models.PmQL.FmpSai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChuKy0h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_0h30");

                    b.Property<double?>("ChuKy10h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h");

                    b.Property<double?>("ChuKy10h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h30");

                    b.Property<double?>("ChuKy11h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h");

                    b.Property<double?>("ChuKy11h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h30");

                    b.Property<double?>("ChuKy12h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h");

                    b.Property<double?>("ChuKy12h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h30");

                    b.Property<double?>("ChuKy13h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h");

                    b.Property<double?>("ChuKy13h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h30");

                    b.Property<double?>("ChuKy14h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h");

                    b.Property<double?>("ChuKy14h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h30");

                    b.Property<double?>("ChuKy15h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h");

                    b.Property<double?>("ChuKy15h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h30");

                    b.Property<double?>("ChuKy16h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h");

                    b.Property<double?>("ChuKy16h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h30");

                    b.Property<double?>("ChuKy17h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h");

                    b.Property<double?>("ChuKy17h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h30");

                    b.Property<double?>("ChuKy18h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h");

                    b.Property<double?>("ChuKy18h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h30");

                    b.Property<double?>("ChuKy19h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h");

                    b.Property<double?>("ChuKy19h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h30");

                    b.Property<double?>("ChuKy1h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h");

                    b.Property<double?>("ChuKy1h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h30");

                    b.Property<double?>("ChuKy20h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h");

                    b.Property<double?>("ChuKy20h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h30");

                    b.Property<double?>("ChuKy21h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h");

                    b.Property<double?>("ChuKy21h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h30");

                    b.Property<double?>("ChuKy22h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h");

                    b.Property<double?>("ChuKy22h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h30");

                    b.Property<double?>("ChuKy23h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h");

                    b.Property<double?>("ChuKy23h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h30");

                    b.Property<double?>("ChuKy24h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_24h");

                    b.Property<double?>("ChuKy2h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h");

                    b.Property<double?>("ChuKy2h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h30");

                    b.Property<double?>("ChuKy3h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h");

                    b.Property<double?>("ChuKy3h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h30");

                    b.Property<double?>("ChuKy4h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h");

                    b.Property<double?>("ChuKy4h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h30");

                    b.Property<double?>("ChuKy5h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h");

                    b.Property<double?>("ChuKy5h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h30");

                    b.Property<double?>("ChuKy6h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h");

                    b.Property<double?>("ChuKy6h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h30");

                    b.Property<double?>("ChuKy7h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h");

                    b.Property<double?>("ChuKy7h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h30");

                    b.Property<double?>("ChuKy8h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h");

                    b.Property<double?>("ChuKy8h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h30");

                    b.Property<double?>("ChuKy9h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h");

                    b.Property<double?>("ChuKy9h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h30");

                    b.Property<string>("Gia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int");

                    b.Property<double?>("Tong")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__FMP_Sai__3214EC27170C2A0C");

                    b.ToTable("FMP_Sai", (string)null);
                });

            modelBuilder.Entity("TestV3.Models.PmQL.NhapGiaNm", b =>
                {
                    b.Property<string>("Giá")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Ngày")
                        .HasColumnType("float");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("NhapGiaNM", (string)null);
                });

            modelBuilder.Entity("TestV3.Models.PmQL.PmA0", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Column0h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_0h30");

                    b.Property<string>("Column10h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_10h");

                    b.Property<string>("Column10h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_10h30");

                    b.Property<string>("Column11h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_11h");

                    b.Property<string>("Column11h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_11h30");

                    b.Property<string>("Column12h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_12h");

                    b.Property<string>("Column12h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_12h30");

                    b.Property<string>("Column13h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_13h");

                    b.Property<string>("Column13h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_13h30");

                    b.Property<string>("Column14h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_14h");

                    b.Property<string>("Column14h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_14h30");

                    b.Property<string>("Column15h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_15h");

                    b.Property<string>("Column15h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_15h30");

                    b.Property<string>("Column16h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_16h");

                    b.Property<string>("Column16h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_16h30");

                    b.Property<string>("Column17h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_17h");

                    b.Property<string>("Column17h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_17h30");

                    b.Property<string>("Column18h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_18h");

                    b.Property<string>("Column18h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_18h30");

                    b.Property<string>("Column19h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_19h");

                    b.Property<string>("Column19h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_19h30");

                    b.Property<string>("Column1h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_1h");

                    b.Property<string>("Column1h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_1h30");

                    b.Property<string>("Column20h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_20h");

                    b.Property<string>("Column20h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_20h30");

                    b.Property<string>("Column21h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_21h");

                    b.Property<string>("Column21h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_21h30");

                    b.Property<string>("Column22h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_22h");

                    b.Property<string>("Column22h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_22h30");

                    b.Property<string>("Column23h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_23h");

                    b.Property<string>("Column23h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_23h30");

                    b.Property<string>("Column24h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_24h");

                    b.Property<string>("Column2h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_2h");

                    b.Property<string>("Column2h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_2h30");

                    b.Property<string>("Column3h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_3h");

                    b.Property<string>("Column3h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_3h30");

                    b.Property<string>("Column4h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_4h");

                    b.Property<string>("Column4h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_4h30");

                    b.Property<string>("Column5h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_5h");

                    b.Property<string>("Column5h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_5h30");

                    b.Property<string>("Column6h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_6h");

                    b.Property<string>("Column6h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_6h30");

                    b.Property<string>("Column7h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_7h");

                    b.Property<string>("Column7h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_7h30");

                    b.Property<string>("Column8h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_8h");

                    b.Property<string>("Column8h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_8h30");

                    b.Property<string>("Column9h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_9h");

                    b.Property<string>("Column9h30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Column_9h30");

                    b.Property<string>("Giá")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ngày")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tổng")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Pm_A0__3214EC07AD44270A");

                    b.ToTable("Pm_A0", (string)null);
                });

            modelBuilder.Entity("TestV3.Models.PmQL.PmEvn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChuKy0h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_0h30");

                    b.Property<double?>("ChuKy10h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h");

                    b.Property<double?>("ChuKy10h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h30");

                    b.Property<double?>("ChuKy11h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h");

                    b.Property<double?>("ChuKy11h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h30");

                    b.Property<double?>("ChuKy12h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h");

                    b.Property<double?>("ChuKy12h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h30");

                    b.Property<double?>("ChuKy13h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h");

                    b.Property<double?>("ChuKy13h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h30");

                    b.Property<double?>("ChuKy14h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h");

                    b.Property<double?>("ChuKy14h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h30");

                    b.Property<double?>("ChuKy15h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h");

                    b.Property<double?>("ChuKy15h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h30");

                    b.Property<double?>("ChuKy16h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h");

                    b.Property<double?>("ChuKy16h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h30");

                    b.Property<double?>("ChuKy17h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h");

                    b.Property<double?>("ChuKy17h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h30");

                    b.Property<double?>("ChuKy18h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h");

                    b.Property<double?>("ChuKy18h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h30");

                    b.Property<double?>("ChuKy19h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h");

                    b.Property<double?>("ChuKy19h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h30");

                    b.Property<double?>("ChuKy1h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h");

                    b.Property<double?>("ChuKy1h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h30");

                    b.Property<double?>("ChuKy20h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h");

                    b.Property<double?>("ChuKy20h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h30");

                    b.Property<double?>("ChuKy21h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h");

                    b.Property<double?>("ChuKy21h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h30");

                    b.Property<double?>("ChuKy22h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h");

                    b.Property<double?>("ChuKy22h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h30");

                    b.Property<double?>("ChuKy23h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h");

                    b.Property<double?>("ChuKy23h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h30");

                    b.Property<double?>("ChuKy24h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_24h");

                    b.Property<double?>("ChuKy2h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h");

                    b.Property<double?>("ChuKy2h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h30");

                    b.Property<double?>("ChuKy3h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h");

                    b.Property<double?>("ChuKy3h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h30");

                    b.Property<double?>("ChuKy4h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h");

                    b.Property<double?>("ChuKy4h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h30");

                    b.Property<double?>("ChuKy5h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h");

                    b.Property<double?>("ChuKy5h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h30");

                    b.Property<double?>("ChuKy6h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h");

                    b.Property<double?>("ChuKy6h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h30");

                    b.Property<double?>("ChuKy7h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h");

                    b.Property<double?>("ChuKy7h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h30");

                    b.Property<double?>("ChuKy8h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h");

                    b.Property<double?>("ChuKy8h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h30");

                    b.Property<double?>("ChuKy9h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h");

                    b.Property<double?>("ChuKy9h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h30");

                    b.Property<string>("Gia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int");

                    b.Property<double?>("Tong")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Pm_EVN__3214EC2785F2DA27");

                    b.ToTable("Pm_EVN", (string)null);
                });

            modelBuilder.Entity("TestV3.Models.PmQL.PmSai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChuKy0h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_0h30");

                    b.Property<double?>("ChuKy10h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h");

                    b.Property<double?>("ChuKy10h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h30");

                    b.Property<double?>("ChuKy11h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h");

                    b.Property<double?>("ChuKy11h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h30");

                    b.Property<double?>("ChuKy12h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h");

                    b.Property<double?>("ChuKy12h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h30");

                    b.Property<double?>("ChuKy13h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h");

                    b.Property<double?>("ChuKy13h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h30");

                    b.Property<double?>("ChuKy14h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h");

                    b.Property<double?>("ChuKy14h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h30");

                    b.Property<double?>("ChuKy15h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h");

                    b.Property<double?>("ChuKy15h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h30");

                    b.Property<double?>("ChuKy16h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h");

                    b.Property<double?>("ChuKy16h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h30");

                    b.Property<double?>("ChuKy17h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h");

                    b.Property<double?>("ChuKy17h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h30");

                    b.Property<double?>("ChuKy18h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h");

                    b.Property<double?>("ChuKy18h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h30");

                    b.Property<double?>("ChuKy19h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h");

                    b.Property<double?>("ChuKy19h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h30");

                    b.Property<double?>("ChuKy1h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h");

                    b.Property<double?>("ChuKy1h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h30");

                    b.Property<double?>("ChuKy20h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h");

                    b.Property<double?>("ChuKy20h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h30");

                    b.Property<double?>("ChuKy21h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h");

                    b.Property<double?>("ChuKy21h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h30");

                    b.Property<double?>("ChuKy22h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h");

                    b.Property<double?>("ChuKy22h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h30");

                    b.Property<double?>("ChuKy23h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h");

                    b.Property<double?>("ChuKy23h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h30");

                    b.Property<double?>("ChuKy24h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_24h");

                    b.Property<double?>("ChuKy2h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h");

                    b.Property<double?>("ChuKy2h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h30");

                    b.Property<double?>("ChuKy3h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h");

                    b.Property<double?>("ChuKy3h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h30");

                    b.Property<double?>("ChuKy4h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h");

                    b.Property<double?>("ChuKy4h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h30");

                    b.Property<double?>("ChuKy5h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h");

                    b.Property<double?>("ChuKy5h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h30");

                    b.Property<double?>("ChuKy6h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h");

                    b.Property<double?>("ChuKy6h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h30");

                    b.Property<double?>("ChuKy7h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h");

                    b.Property<double?>("ChuKy7h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h30");

                    b.Property<double?>("ChuKy8h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h");

                    b.Property<double?>("ChuKy8h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h30");

                    b.Property<double?>("ChuKy9h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h");

                    b.Property<double?>("ChuKy9h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h30");

                    b.Property<string>("Gia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int");

                    b.Property<double?>("Tong")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Pm_Sai__3214EC27AFA1BCFF");

                    b.ToTable("Pm_Sai", (string)null);
                });

            modelBuilder.Entity("TestV3.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
